//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual MedicineType MedicineType { get; set; }
    }
}
